### ISSUE TITLE
Disable tekst i input felt

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#10]
Hei, har kjørt en del brukertester de siste dagene, og bruker blant annet et disabled input-felt. Det står alene, og det er ingen andre input-felter i nærheten.
Det ser veldig klikkbart ut, så folk tror de kan trykke der, selv om det er disabled.
- Nina Bakken (Designer Helse område)

**Comment by karinaldw** [comment]
God diskusjon på #designsystem på slack. Noen ressurser og argumenter som ble nevnt der: 

/Jeg har tidligere bestemt meg for å ikke bruke deaktiverte elementer; jeg har sett altfor mange som ikke skjønner at et element kan deaktiveres, og som bare klikker og klikker uten hell. Videre er ofte kontrastnivået lavere på sånne elementer. Jeg mener det er bedre å vise interaksjonselementet som vanlig, og ved klikk gi en feilmelding om akkurat det som mangler, for å (a) unngå sånn forvirring, og (b) kunne vise til akkurat det svaret som er savnet.

/Når det skaper forvirring og ser klikkbart ut, ville jeg nok gått for at det dukket opp ved valg av radioknappen. @christine.joy.atherton har forøvrig skrevet veldig godt om disablede elementer: https://uxdesign.cc/why-you-shouldnt-include-disabled-interaction-elements-in-your-design-system-76a2d4307faf

/Enig i at deaktiverte elementer er meget uheldige. Vanskelig å skjønne at de er deaktiverte, og det kan bli en veldig frustrerende opplevelse for mange. Spesielt for folk som er stresset eller har andre kognitive utfordringer.

Varierende skjermleserstøtte for dem også: https://tink.uk/screen-reader-support-for-disabled-read-only-form-fields/

Som grunnregel burde vi ikke bruke deaktiverte elementer i det hele tatt, heller vise en feilmelding hvis brukeren prøver å bruke noen hun ikke har lov til (eller skjule elementet hvis det ikke er relevant at det er der).

@finiteattention

**Comment by randisolli** [comment]
Her bør vi også oppdatere tekst/veiledning på design.nav.no for at man helst skal unngå å bruke "disabled" input felt, slik som beskrevet for knapper her:
https://design.nav.no/components/knapp

<img width="756" alt="Screenshot 2020-07-07 at 10 21 17" src="https://user-images.githubusercontent.com/63231600/86746936-b4f85b00-c03b-11ea-9125-3efeef7c59ae.png">

**Comment by KenAJoh** [comment]
Fullført med navikt/nav-frontend-moduler#753
