### ISSUE TITLE
Lage forslag til ny meny-struktur i Sketch-bibliotek

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#107]
- Menyene i Sketch-biblioteket må ryddes og restruktureres. Begynn med å sette opp en skisse til ny struktur.

**Comment by Vikingwind** [comment]
Ta sammen med komponentoversikt

**Comment by Lillebo** [comment]
Løst med [denne Sketch-oppdateringen](https://nav-it.slack.com/archives/C7NE7A8UF/p1580898940061600)
