### ISSUE TITLE
Typografi-komponenten "Element" skal være semi-bold, ikke bold

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#117]

**Comment by unorsk** [comment]
Hva er grunnlag til det?

Nå ser jeg at *Element* har font-weight på 600 og det kan regnes som semi-bold, antar jeg. Men det kan henge av fonten selv.

Også fikk jeg inntrykk at vi har en usikkerhet om hvordan Sketch sine medium/bold/semi-bold tolkes til font-weight punkter.

![image](https://user-images.githubusercontent.com/25188/72141699-a0405080-3393-11ea-8e35-e5b69e93d998.png)

**Comment by Miaag** [comment]
Landet på at vi lager en prototype i kode med skisser på semibold vs bold mot normal tekst.

**Comment by Lillebo** [comment]
Løst med [denne Sketch-oppdateringen](https://nav-it.slack.com/archives/C7NE7A8UF/p1580898940061600)

Opprettet eget issue for videre generell revurdering av semibold/bold: #156
