### ISSUE TITLE
Tilsette favicon i NAV Frontend

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#118]
Favicon kan lastes ned herfra: https://www.dropbox.com/sh/8ixgi72hrzsyp37/AAC35XIhweQc_EGeHBi7IaL0a?dl=0

**Comment by Lillebo** [comment]
Så dere mener at dette:
<img width="29" alt="Screenshot 2019-12-02 at 16 01 22" src="https://user-images.githubusercontent.com/74510/69969652-1cd24a80-151d-11ea-9e4d-2716b4e8c009.png">

...er bedre enn dette?
![Tilsette_favicon_i_NAV_Frontend_·_Issue_#118_·_nav_2019-12-02_18-56-16](https://user-images.githubusercontent.com/74510/69982739-7b0b2780-1535-11ea-951c-24d9a499c437.png)

@MathildeSkjelbostad

**Comment by MathildeSkjelbostad** [comment]
Kan du si hva du mener ikke er bedre, for det er slik jeg forstår spørsmålet ditt? Jeg foretrekker konstruktive tilbakemeldinger, lettere å svare på. Den runde logoen, uten skråstreker, er ikke i henhold til logobruken vår. Derfor har vi utforsket alternativer og landet på denne varianten - den er litt lenger unna logoen (font og form), men fortsatt tydelig i fargebruken

**Comment by Lillebo** [comment]
Hm, skulle tro det var åpenbart enklere å identifisere Nav på den nederste av de to? Med så små størrelser så går det jo nesten ikke an å se hva som står uansett. Da kan den nederste i det minste støtte seg noe på gjenkjennelses-effekten til logoen vår? Hadde det ikke vært enklere å bare tillate å bruke logoen uten skråstreker til slike avgrensede formål? Hva er risikoen her? Ser f.eks. at designmanualen bl.a. begrunner logoen med at det aldri skal være noe tvil om hvem avsenderen i vår kommunikasjon er. Vil ikke dette prinsippet bare svekkes av at dere lager en helt ny logo her? Hva er fordelen av å ha en helt ny logo til slike formål? 

Det hadde jo vært synd hvis hovedfokuset her bare handler om å etterleve gamle retningslinjer som åpenbart glemte å ta høyde for slike ting...

Lurer forøvrig også litt på hva dere mener med å "tilsette i frontend"? Hva er det dere egentlig ber oss om å gjøre?

**Comment by ghost** [comment]
Nå en gylden mulighet til å se på branding i digitale flater 😊 Få en tydelig logo som fungerer på små flater og SOME kanaler. I flere av disse kanalene må logoen fungere i sirkel format. De fleste brand har et symbol, uten tekst. De har laget et tydelig symbol som folk kjenner igjen, da plassen er så liten og tekst "gror" velger mange dette. Men viktig at logoen oppleves som NAV er avsender. NAV logen er vel ganske kjent, og folk husker vel den som er sirkel. Da vil gjenkjenningseffekt være tydligere med en sirkel i digitale flater å?

Forslag:
• Sirkel for med "nav" men da gått inn og "skarpet" opp at pixler ikke gror. (Logo font)
• Blir det tydlig nok f.eks kun med bokstaven "n" i nav logo fonten med en rød sirkel?

**Comment by sergiohaisch** [comment]
Helt enig @chrisarnesen, og vi tester litt forskjellige varianter. Men vi er ikke der enda, og det er en små del av en stor jobb. I mellomtiden kan vi i hvertfall prøve å ikke bryte med våre egne logo regler.

**Comment by MathildeSkjelbostad** [comment]
Jeg er enig i tankegangen Chris nevner, og det er mye av det Sergio og jeg har diskutert. 

Vi har masse vi er nødt til å ta tak i fremover, slik at vi klarer å fremstå helhetlige i alle flater. Det innebærer for eksempel å se på hvordan vi bruker logoen vår.
Per nå har vi ikke kapasitet til å prioritere den type jobb, da det vil kreve tid og ressurser. Derfor har vi, som Sergio nevner, en mellomløsning som gjør at vi i hvert fall ikke bryter logoreglene. Det betyr ikke at "jobben er gjort og vi kan gå hjem", dette er en kontinuerlig prosess.

Først i rekka er å få inn profilelementer i Frontify. På den måten kan vi synliggjøre hvor vi har hull vi må få gjort noe med, for eksempel et favikon. Jeg tar med meg forslagene og tankene videre, som vil være ekstremt nyttig når vi får mulighet til å gjøre et mer gjennomført arbeid.

Derfor håper jeg at dette nye favikonet kan bli lagt inn i biblioteket? Akkurat hvordan det skjer kan jo jeg svært lite om, men den må i hvert fall tilgjengeliggjøres på en eller annen måte :)

**Comment by Miaag** [comment]
Hei, ref det du skriver over Mathilde, for bakgrunn til endring: _"Den runde logoen, uten skråstreker, er ikke i henhold til logobruken vår. Derfor har vi utforsket alternativer og landet på denne varianten - den er litt lenger unna logoen (font og form), men fortsatt tydelig i fargebruken."_  Kan vi ikke justere på disse logoreglene/retningslinjene når vi nå er i gang med å tilrettelegge for bruken av logoen i digitale flater? Bedre å justere reglene underveis enn å følge ufullstendige regler som ikke har tatt høyde for digitale flater. Hvis man ikke justerer underveis må alt som gjøres nå som følger ufullstendige retningslinjer gjøres om igjen uansett. Og det må da veie tyngre at nav logoens største gjenkjenbarhet er den runde sirkelen, enn at skråstrekene ikke får plass? **Hovedsakelig er det en større endring å gjøre sirkelen om til en firkant, enn å bare fjerne skråstrekene i digitale flater.** Er den firkantede logoen kun forbehold faviconet? Uansett syns jeg vi burde beholde hovedformen på logoen i aller største grad.

**Comment by MathildeSkjelbostad** [comment]
Kun forbeholdt favikonet, det er absolutt ingen planer om at selve NAV-logoen skal gjøres firkantet på digitale flater. Dette er en bitteliten endring av et bittelite ikon, som var enkelt å få gjort noe med for å være i tråd med reglene per i dag. Vi må generelt se på hvor liten logoen kan være, før skråstrekene burde fjernes og selve "nav" blir for blurry, og få opp noen regler for det. Det blir ikke gjort på en dag.

Men det er som sagt ikke noe vi kommer til å prioritere nå før jul, og jeg kommer derfor til å legge denne diskusjonen død nå, frem til vi har mulighet til å se ordentlig på det - i faktiske møter, med involvering av personer som skal kunne få sagt sin mening. Det er ikke en diskusjon som skal tas i Github, og jeg kommer ikke til å redegjøre videre for dette valget her.

Om det er slik at dere ikke kan/ønsker å få lagt det inn, så er det en helt annen prat enn hvorvidt formen/fonten/skråstrekene er riktig eller feil. Og igjen, ikke en prat som skal tas i Github.

**Comment by Miaag** [comment]
Nå er det sånn at det har vært ønsket å ta diskusjoner i github for designsystemet og alle involverte der for å kunne vise til senere. Men ikke alltid greit å diskutere over tastaturet nei. Men når det kun gjelder et favicon, så blir det neste litt tullete å ta en fysisk møte på det:) Jeg ville bare få det helt klart på slutten der at dette bare handlet om et favicon, siden det ble nevnt logoen i sosiale medier også høyere opp her. Men i all hovedsak så handler kommentaren min om at forbedringer og mangler ifh til logoen burde gå i favør av logoens gjenkjennbarhet, og ikke mangel på retningslinjer.

**Comment by Lillebo** [comment]
Jeg tenker kanskje det bare er fordelaktig å ta slike diskusjoner her. Åpenhet = ryddighet :+1:

>[...] det er absolutt ingen planer om at selve NAV-logoen skal gjøres firkantet på digitale flater. Dette er en bitteliten endring av et bittelite ikon [...]

Men dere har jo levert nye faviconer med oppløsning opp til hele 96x96 piksler?

![favicon-96x96](https://user-images.githubusercontent.com/74510/70070415-dd2a6200-15f3-11ea-8d44-f7698964bfac.png)

>[...] I mellomtiden kan vi i hvertfall prøve å ikke bryte med våre egne logo regler.

>[...] som var enkelt å få gjort noe med for å være i tråd med reglene per i dag. [...]

Sliter fortsatt med å forstå hvordan det å lage en helt ny logo - med et helt nytt uttrykk - på noen som helst måte kan sies å være i tråd med dagens logo-regler? 🤔

Kanskje vi bare kan bli enige om at dette burde bearbeides litt mer før det publiseres/tilgjengeliggjøres/oppdateres noe sted?

**Comment by PrebenAas** [comment]
Jeg synes det ikke ser ille ut i verktøylinja i Chorme - muligens alligne "nav" i sirkelen, det virker som "nav" ligger noe vertikalt allignet ned (under center).

![image](https://user-images.githubusercontent.com/20104610/70131846-49a07200-1683-11ea-8dbe-eec85566192f.png)

**Comment by ghost** [comment]
Det er nok slik logoen er designet, at navntrekket ligger under senter punktet i sirkel.

**Comment by ghost** [comment]
Se vedlagt fil. Nytt Favikon er “blur” i nettleser vindu.

Om man ikke skal bruke sirkel lenger, er det en idé å bruke “nav” fonten likevel?

Hva skal vi publisere @MathildeSkjelbostad?

<img width="476" alt="Favikon" src="https://user-images.githubusercontent.com/50408627/72437778-d28eeb00-37a3-11ea-9823-8c2d98dd676f.png">

**Comment by MathildeSkjelbostad** [comment]
@chrisarnesen Jeg avslutter dette issuet, og så ser vi på det med friske øyne senere
