### ISSUE TITLE
Etikett-komponenten har ulik størrelse i sketch og front end

### ISSUE THREAD

**Issue by ElinNav** [navikt/Designsystemet-old#123]
Sketch - 24 høy. 14 px font
Front end - 32 høy, 16 px font.

**Comment by Lilyngs** [comment]
Vi trenger en liten størrelse for interne flater, 24 px høy.

Står man forresten fritt til å velge farge selv @Lillebo ? Vi har nå en etikett som brukes til å vise en død person. Denne har fått fargen mørk grå bg og hvit tekst. Og er en etikett som bør gjenbrukes på tvers av alle interne flater.

**Comment by Lillebo** [comment]
Bør løses samtidig som #122
Ref. duplikat issue #142: bør også vurdere å bruke samme stil på disse som Alertstriper
