### ISSUE TITLE
Lage frontend-komponenter av inline Alertstriper

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#139]
<img width="882" alt="Screenshot 2020-01-30 at 12 39 18" src="https://user-images.githubusercontent.com/74510/73446773-b96a6a80-435d-11ea-8e33-a553f42f1d14.png">

**Comment by unorsk** [comment]
Kan det ikke funke som css-styles? Og hvilke skisser som skal brukes til de?

**Comment by Lillebo** [comment]
Har oppdatert issuet med skjermbilde av skisser 👍Tror kanskje vi skal unngå **bold** styling på teksten i første omgang. Innholdet i disse komponentene kan jo uansett bestemmes fritt av konsumenten som HTML via `children` - så vi trenger ikke låse komponenten til bold her.

Tenker disse helt sikkert kan løses med nesten bare CSS ja, og at vi egentlig bare trenger en ny prop på de eksisterende komponentene. Men ønsker helst å unngå flere `boolean` props, så kanskje noe ala:

```tsx
<Alertstripe form="inline" />
```

I stedet for:

```tsx
<Alertstripe inline />"
```

Eller noe sånt? 🤔

**Comment by Lillebo** [comment]
Løst med https://github.com/navikt/nav-frontend-moduler/pull/657
