### ISSUE TITLE
Lenke til komponent (github) i hver komponent side 

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#14]
Vil gjerne få en lenke i komponent sidene (design.nav.no), til hver komponent i github så at kan kan melde issues uten å måte lette i repoen.

**Comment by randisolli** [comment]
@KenAJoh kan sjekke om det er en enkel fiks eller om det tar litt mer tid.

**Comment by KenAJoh** [comment]
Er nå en feature på design.nav.no
