### ISSUE TITLE
Vurdere å avvikle Knapp med spinner

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#145]
Trenger Knapp å støtte spinner? Kan ikke spinner være andre steder enn inne i knappene når applikasjonene laster?

Relatert til #131

**Comment by randisolli** [comment]
@KenAJoh sjekk hva denne går ut på.

**Comment by KenAJoh** [comment]
Har bestemt oss for å ikke avvikle Knapp med spinner. Eventuell erstatning for løsning vil være unødvendig kompleks med tanke på UU og dette er en grei løsning for nå.
