### ISSUE TITLE
Bør FnrInput ha lengde begrenset til 11 siffer som default?

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#147]
Ref. [Slack-forespørsel](https://nav-it.slack.com/archives/C7NE7A8UF/p1580819334053800?thread_ts=1580817868.051100&cid=C7NE7A8UF)

Bør det gjelde både fysisk lengde og antall tegn den aksepterer?

https://design.nav.no/components/fnrinput

**Comment by erlendev** [comment]
Nei, jeg syns ikke det er lurt å sette den begrensningen. Kan man ikke heller åpne for at teamene kan sette `maxLength` dersom det gir mening for dem? Tenker det er dumt å fjerne muligheten for å gi beskjed til brukerne om at det man har skrevet inn i feltet er for langt - hvorfor et fødselsnummer er ugyldig er ikke alltid innlysende, og det er nyttig å kunne si om det bruker har tastet inn er for kort, for langt, eller bare er på ugyldig format.

**Comment by frodehansen2** [comment]
Enig med Erlend. Og når en først åpner for at komponenten har litt, bør den kanskje også håndtere ulike måter en bruker kan legge inn fnr på? Dette er kanskje noen copy-paster, og da er det kanskje formatert med space. Så det hadde vært fint om komponenten blir robust nok til å takle de mest vanlige måtene fnummeret er formatert på. Sånn sett kunne en kanskje fått info om det gyldige nummeret var fnr eller dnr?

**Comment by karinaldw** [comment]
Enig i at det kan være lurt å satse på feilmelding istedenfor maks antall tegn. Tror likevel at det er lurt å visuelt ha den på 11 tegn, slik at det gir en indikasjon på hvor lang input som er forventet.

**Comment by Lillebo** [comment]
Enig med alle 👍 Foreslår at vi legger inn eksplisitt bruk av `bredde="S"` i eksemplene på komponent-siden + at vi legger inn en liten oppfordring til å bruke dette på komponentens tilgjengelighets-fane, med en peker hit: https://design.nav.no/components/input#lengde

**Comment by KenAJoh** [comment]
Fikset med navikt/nav-frontend-moduler#711
