### ISSUE TITLE
Mangler innhold om Alt-text under accessibility fanen

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#148]
Siden har ikke innhold, @karinaldw publiserer du innhold som ble utarbeidet? Eller er det kun teknisk feil nå at innhold ikke lastes?

https://design.nav.no/accessibility/alt-text

**Comment by Lillebo** [comment]
Hm, det ser ut som en ny teknisk feil ja. Takk for at du melder ifra 👍

**Comment by Lillebo** [comment]
Fikset med denne: https://github.com/navikt/nav-frontend-moduler/pull/668
