### ISSUE TITLE
Oppdatere innhold om Tools under accessibility fanen

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#149]
Snakket med David, kan det være lurt å si hvilke av disse verktøyene DigiDir bruker? Som en kvalitets garanti?

Her er lista: 
https://inklud.no/verktoy-digdir-bruker-under-universell-utforming-tilsynet/?fbclid=IwAR3BzFJpi5QaAGHRR7DV0TEdlCuNrJGpTgTl00Fgv_jhSsLh0nw42DqLcoI

**Comment by Lillebo** [comment]
God idé 👍

**Comment by karinaldw** [comment]
Det her kommer til å endre seg om ikke så lenge. Digdir er med i WAI-tools-prosjekt og tester ut nye verktøy de skal kjøre fremover. Men kan være lurt å ta med W3Cs kodevalidator og markere at tilsynet har brukt siteimprove.

**Comment by karinaldw** [comment]
@Lillebo, jeg kan fikse markdown-fil, men hvor finner jeg det igjen?

**Comment by Lillebo** [comment]
https://github.com/navikt/nav-frontend-moduler/blob/master/guideline-app/app/ui/containers/accessibility/tools/AccessibilityTools.mdx 🙂

**Comment by karinaldw** [comment]
Da har jeg lagt inn endringer.

**Comment by Lillebo** [comment]
Fikset med https://github.com/navikt/nav-frontend-moduler/pull/697
