### ISSUE TITLE
Hvitt NAV logo er ikke lenger med i oppdatert Sketch bibliotek

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#151]
I nytt bibliotek er det kun rød og stort logo som er tilgjengelig for bruk.
Feil eller oppdatering i Brand NAV at hvitt logo ikke lenger skal brukes?

**Comment by Lillebo** [comment]
Hvit NAV-logo skal ligge her i det nye biblioteket: 🙂

<img width="872" alt="Screenshot 2020-02-12 at 09 47 46" src="https://user-images.githubusercontent.com/74510/74318071-d13de780-4d7c-11ea-946f-152d2ccec5eb.png">
