### ISSUE TITLE
Meny knapp med chevron – Feil farge på chevron i Sketch

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#152]
I frontend er chevron blå, i Sketch er det sort.

**Comment by nutgaard** [comment]
I nav-frontend styres fargen av chevron etter tekst-fargen der den blir brukt. 
E.g eksemplet her; https://design.nav.no/components/chevron/ så er chevron `navMorkGra` siden det er tekst-fargen for siden.

**Comment by Lillebo** [comment]
Ser ut som alt er som det skal være i Sketch nå. Kan det hende du forvekslet Menyknapp med Select?

<img width="314" alt="Screenshot 2020-02-14 at 12 10 38" src="https://user-images.githubusercontent.com/74510/74526218-2e739d80-4f23-11ea-8977-1408612a4302.png">
