### ISSUE TITLE
Chevron retning "down"

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#154]
Skal man ikke kunne bruke chevron som peker nedover? I Sketch biblioteket finnes de fleste andre retninger med ikke en som peker nedover.

<img width="380" alt="Chevron_retning" src="https://user-images.githubusercontent.com/50408627/73927542-df4dbd00-48d1-11ea-91a9-3ca3f1fd0e21.png">

**Comment by Lillebo** [comment]
Ser ut som dette er fikset nå. Prøv å oppdater UI-biblioteket ditt 🙂

<img width="397" alt="Screenshot 2020-02-14 at 12 08 26" src="https://user-images.githubusercontent.com/74510/74526034-cc1a9d00-4f22-11ea-9ce1-a7a65d36257a.png">
