### ISSUE TITLE
Utforske nye designretninger på nav.no

### ISSUE THREAD

**Issue by Miaag** [navikt/Designsystemet-old#157]
- Skisse opp ulike retninger for nav.no
- Skissene er for diskusjon og videre arbeid med TP og skal ikke være et endelig forslag i denne omgang.

**Comment by Lillebo** [comment]
Bør avvente videre arbeid på dette inntil arbeidet med #160 har kommet videre.

**Comment by randisolli** [comment]
Se også i sammenheng med #162

**Comment by randisolli** [comment]
Sy sammen med Tuva sin del, samt lage en versjon 3 (med flere nivå i sidepanel som Gov.uk)

**Comment by randisolli** [comment]
@Vikingwind har oppdatert skissene og prototypen. Neste steg blir gjennomgang med Team Personbruker i sammenheng med prosjektet for nye nav.no.

**Comment by KenAJoh** [comment]
Er under arbeid i og utenfor designsystemet
