### ISSUE TITLE
Designsystem bibliotek migrering til Figma for testing

### ISSUE THREAD

**Issue by Miaag** [navikt/Designsystemet-old#163]
Bakgrunn:
I arbeidet med å finne ut hvilket program designere skal jobbe i og hvor vi skal etablere designsystem biblioteket så er det over tid testet ulike programmer. Figma ser ut til å løse de fleste behov i ett og samme prpgram. Etter møtet angående bruk av programmer og veien videre:
- Så er det ønsket å teste Figma i større skala.
- Vi trenger å få lagt opp biblioteket i Figma for ordentlig testing og vurdering av programmet.

**Comment by Vikingwind** [comment]
Ferdig
