### ISSUE TITLE
Burde vi åpne for inaktive valg i checkbokspanelgruppe?

### ISSUE THREAD

**Issue by karinaldw** [navikt/Designsystemet-old#166]
Valg i checkbokspanelgruppe kan settes på disabled. 
https://design.nav.no/components/checkbokspanelgruppe

Dette bryter med hvordan vi vanligvis håndterer ting som ikke kan velges. Normalt sier vi at det ikke skal være inaktive valg, men gode feilmeldinger, slik at man får med seg hvorfor man ikke får tatt det valget. 

Finner forresten ikke lenger hvor det står tydelig i designsystemet, så kan hende vi burde fremheve dette bedre på tilgjengelighetssidene.

Er det noen gode argumenter FOR å ha inaktive valg her?

**Comment by Lillebo** [comment]
Hm, dette er et veldig godt spørsmål - og noe som egentlig angår alle skjema-komponentene våre:

https://design.nav.no/components/checkbox#disabled
https://design.nav.no/components/input#disabled
https://design.nav.no/components/radio#disabled
https://design.nav.no/components/radiopanelgruppe
https://design.nav.no/components/select#disabled
https://design.nav.no/components/textarea#disabled

Per nå har vi bare en generell oppfordring til å unngå `disabled` på knapper:

https://design.nav.no/components/knapp#disabled

Men problemstillingen gjelder jo i stor grad skjema-elementene også. Jeg er redd det kan bli vanskelig å fjerne muligheten for å ha slike elementer med `disabled` overhodet - men vi burde muligens utvide oppfordringen til å unngå dette på alle komponentene våre 🤔

Bør kanskje minne om [denne diskusjonen](https://github.com/w3c/wcag21/issues/805) hos W3 her også. Som nevnt tidligere så er jeg litt tilhenger av dette poenget:

>My hypothesis is that the purpose of an element being disabled is to communicate to the user: 1) something is disabled, and 2) the specifics of that disabled element. If the disabled element is not intended to communicate anything, then it should be removed.

**Comment by karinaldw** [comment]
Gir du meg tilgang til md-filene @Lillebo? Da legger jeg inn tekstforslag.

**Comment by Lillebo** [comment]
https://github.com/navikt/nav-frontend-moduler/tree/master/packages/node_modules/nav-frontend-skjema/md 🙂

Er flere komponenter som mangler en `.md`-fil for tilgjengelighet, men kanskje du kan legge inn et felles forslag i denne: https://github.com/navikt/nav-frontend-moduler/blob/master/packages/node_modules/nav-frontend-skjema/md/textarea/Textarea.accessibility.md

Kunne du kopiert det som står om "placeholder" i den fila over til tilgjengelighets-fila for Input også samtidig?

**Comment by randisolli** [comment]
@KenAJoh skriv inn tekst på skjemaelementer hvor vi anbefaler å ikke bruke "inaktiv" checkbox: https://design.nav.no/components/checkbokspanelgruppe

**Comment by KenAJoh** [comment]
Fullført med navikt/nav-frontend-moduler#753
