### ISSUE TITLE
Vurdere en knagg/tags-input komponent

### ISSUE THREAD

**Issue by KenAJoh** [navikt/Designsystemet-old#170]
Allerede i bruk av Modiapersonoversikt

<img width="801" alt="tags-input" src="https://user-images.githubusercontent.com/26967723/79979555-fc8e3280-84a1-11ea-913a-e1fd1c7b6672.png">

**Comment by randisolli** [comment]
@KenAJoh sjekk om du finner Slack diskusjonen(e) som vi kan linke til.

**Comment by randisolli** [comment]
Se også #87

**Comment by KenAJoh** [comment]
Duplicate #87
