### ISSUE TITLE
Alligne checkboxer ved lengre tekster (Figma)

### ISSUE THREAD

**Issue by PrebenAas** [navikt/Designsystemet-old#173]
Bør left-alligne checkboxer "by default" ved lengre tekster på checkbox/gruppe i Figma:

![image](https://user-images.githubusercontent.com/20104610/80465915-187b5380-893c-11ea-9ce0-0786863fdc06.png)

**Comment by randisolli** [comment]
Jeg oppdaterte denne til å være venstrejustert i Figma library nå @PrebenAas.

**Comment by PrebenAas** [comment]
Perfekt, funker nå @randisolli :)
