### ISSUE TITLE
Oppdatere lukk-knapp i Modal i Figma

### ISSUE THREAD

**Issue by PrebenAas** [navikt/Designsystemet-old#176]
I Figma legger jeg inn "modal":
![image](https://user-images.githubusercontent.com/20104610/83112972-41237400-a0c7-11ea-82b0-56c33e7bb41b.png)

Designsystemet (og React) bruker en annen modal som er noe tydeligere:

![image](https://user-images.githubusercontent.com/20104610/83113265-b5f6ae00-a0c7-11ea-8f39-7ed1d1239c53.png)

https://design.nav.no/components/modal

Hadde vært fint med samsvar, fordi skissene mine ikke stemmer overens med produksjon.

**Comment by KenAJoh** [comment]
Modalen i frontend bruker i dag "Lukknapp". Denne er deprecated og skal erstattes med `XKnapp` fra pakken `ikonknapper`. Blir oppdatert når navikt/nav-frontend-moduler/issues/587 er utført.
