### ISSUE TITLE
Lage egen side for ikonsøk

### ISSUE THREAD

**Issue by KenAJoh** [navikt/Designsystemet-old#189]
> Noe lignende https://components.ruter.as/#/Visual%20Style/Icons
> Fontawsome

> Tester ut storybook for dette og eventuelt chromatic

**Comment by nutgaard** [comment]
Ble laget noe for dette for noen år tilbake, men kunne ikke gå live pga lisensen på ikon-biblioteket.
https://github.com/navikt/nav-frontend-ikoner
https://github.com/navikt/nav-frontend-ikoner-backend

Mulig det er overkill i forhold til hva som trengs nå om dagen, men kan være verdt å ta en titt på.

**Comment by KenAJoh** [comment]
https://design.nav.no/resources/icons
