### ISSUE TITLE
Skjema-grupper har 16px bottom-padding på figma, 8px for komponenter 

### ISSUE THREAD

**Issue by KenAJoh** [navikt/Designsystemet-old#190]
Hvilken av disse er riktige? 
Gjelder RadioGruppe og CheckboxGruppe, men kan vurdere å endre for panel versjonene også?

**Comment by randisolli** [comment]
@KenAJoh Det riktige her er det som ligger i Figma:

- CheckboxGruppe skal ha 16 px
- RadioGruppe skal ha 16 px
- CheckboxpanelGruppe skal ha 8 px (men kan vurdere om 16 px er bedre)
- RadiopanelGruppe skal ha 8 px (men kan vurdere om 16 px er bedre)

**Comment by KenAJoh** [comment]
> * CheckboxpanelGruppe skal ha 8 px (men kan vurdere om 16 px er bedre)
> * RadiopanelGruppe skal ha 8 px (men kan vurdere om 16 px er bedre)

Tenker 8px fungere bra her da det allerede er ganske mye ubrukt rom mellom panelene som gjør at det ikke føles for tett.
