### ISSUE TITLE
Hvordan skal man bidra til systemet?

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#2]

**Comment by Lillebo** [comment]
Retningslinjer for utviklere ligger her: https://github.com/navikt/nav-frontend-moduler/blob/master/CONTRIBUTING.md

**Comment by sergiohaisch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hvordan skal man bidra til systemet?](https://trello.com/c/yPP99vjP/566-hvordan-skal-man-bidra-til-systemet)

**Comment by sergiohaisch** [comment]
Design: https://zpl.io/adzZEAp

**Comment by Lillebo** [comment]
Erstattes av #99
