### ISSUE TITLE
Håndbok for designere

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#20]
Vi publiserer en side for å fortelle om hvordan vi skal designe i NAV.

https://teams.microsoft.com/_#/files/General?threadId=19:25fd723b7b2a4d578136562afc422a51@thread.skype&ctx=channel&context=Kulturworkshop

**Comment by ghost** [comment]
Utkast er publisert og en redaktør gruppe kan redigere og sammenfatte mer content og struktur på innhold.

**Comment by sergiohaisch** [comment]
Utkast til en side er publisert i google sites: https://sites.google.com/view/ds-design-handbok/hei
