### ISSUE TITLE
State "active" i checkboxpanel gir ikke check-mark som ønsket

### ISSUE THREAD

**Issue by PrebenAas** [navikt/Designsystemet-old#21]
![Screenshot 2019-06-20 at 11 56 49](https://user-images.githubusercontent.com/20104610/59840623-ffd10300-9352-11e9-8c41-9368c3e83dd7.png)

Øverst er uendret komponent. I midten er staten endret til "active", og nederst er ønsket "output" når panelet endrer state (som ikke skjer).

**Comment by Vikingwind** [comment]
Dette er fikset i UI biblioteket nå. Bruk bibliotek i Abstract

**Comment by ghost** [comment]
Ikke alle har lisenser til Abstract.
