### ISSUE TITLE
Icon bevarer ikke proportioner ved skalering i "Select label"

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#28]
Justere man størrelse bredde på Select label blir ikonet dratt inn og ikonet er ikke konstant når du drar i elementet selv når man setter på anima.

<img width="422" alt="Select_label_chevron_proportioner" src="https://user-images.githubusercontent.com/50408627/62546202-593db480-b863-11e9-8264-0b77a8f07e42.png">

**Comment by Vikingwind** [comment]
Dette er enkel å fikse, kan ordne i morgen

**Comment by Vikingwind** [comment]
Den ser ok ut, tror biblioteket som ligger i sketch Cloud ikke er oppdatert, skal laste opp på nytt

**Comment by Lillebo** [comment]
Fikset, avhengig av #112

**Comment by Lillebo** [comment]
Fikset med #112
