### ISSUE TITLE
Content area grid – Statiske Sketch skisser

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#30]
Når alle følger de samme reglene, får man automatisk en mer konsistent brukergrensesnitt.

Da vi jobber statisk i Sketch er det fint å ha noen tall kan bygge opp de statiske skissene våre. Satte opp føringer på grid og innholds mål (format)I hvilken formater skal en designer sette opp skissene sine i opp i Sketch.
 
Skjermoppløsning – Destop:
1280 (Artboard)
1024 (Total innholdsområde)
800 (Innholds komponenter)
640 (Tekst innhold område)Format – Mobil:
320 misteformat

Interneflater (Kan også sette opp føringer her):
Design mot 1440 men vær oppmerksom på skalering, mange av veiledere har mer en et vindu åpne, og selv om skjermene er større en 1440, kan selve bruk skjermområde være mindre.  Eksternt designer vi optimalisert for 1280, med en hoved innhold panel på 800 og mulighet til å ekspandere til 1024 totalt.

**Comment by Lillebo** [comment]
Erstattet av epic: https://github.com/navikt/Designsystemet/issues/111
