### ISSUE TITLE
Icon er ikke konstant i Ekspand panelet

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#33]
Ekspand panelet under panel så vil ikke ikonet være konstant når du drar i elementet. Har prøvd anima her også men får det ikke til å fungere.
Skal ikke dette elementet også har mulighet for tekstfelt inni?

<img width="1688" alt="Icon_ikke_konstant_Ekspand_panelet" src="https://user-images.githubusercontent.com/50408627/62618344-49ca7400-b914-11e9-9c31-eb2b5f73ee0e.png">

**Comment by Vikingwind** [comment]
Den kan jeg fikse i morgen.
