### ISSUE TITLE
Plassering utfordring på check og radio i Checkboksgruppe og panelgruppe (Sketch)

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#34]
Både med checkboksgruppe og panelgruppe får jeg ikke satt selve check eller radio konstant i hjørnet med anima. Brukerfeil eller er det innstillinger?

**Comment by Lillebo** [comment]
Antar denne kan lukkes da de siste versjonene av Sketch-biblioteket ikke lenger bruker anima-plugins? Hvis du fortsatt opplever problemer med dette skal du bare gjenåpne issuet @chrisarnesen 🙂
