### ISSUE TITLE
Mangler blått check og radio symbol

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#35]
Man får skiftet bakgrunnsfargen under panel ved å velge blå states, men får ikke valgt blått symbol/ikon for check eller radio.

Det ligger ikke noe tilgang til å endre ikon i høyre kolonen.

<img width="717" alt="Mangler_blue_check_radio_symbol" src="https://user-images.githubusercontent.com/50408627/62626685-3923f900-b928-11e9-9740-6d7b71fe34d3.png">

Kan det ha noe med at den er linket hit, og her finner man ikke ikonet, for er bare staten på firkanten

<img width="293" alt="state_firkant" src="https://user-images.githubusercontent.com/50408627/62627101-06c6cb80-b929-11e9-9c2e-0d6a7e115b3c.png">

**Comment by Vikingwind** [comment]
Checkbox er fikset
