### ISSUE TITLE
Tilbakemeldings modul

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#39]
Det utarbeides en Tilbakemeldings modul som er brukertestet: Den ferdigstilles og løftes opp i systemet.

Vi må sette opp regler for brukt og dele kode og komponenter i systemet.

**Comment by Lillebo** [comment]
Vi avventer pull request fra Team Vibe/Voff.

**Comment by KenAJoh** [comment]
Er utformet en tilbakemeldings-komponent av sommerstudentene 2020, lokalisert her: 
https://github.com/navikt/nav-dekoratoren/tree/master/src/komponenter/footer/feedback
