### ISSUE TITLE
Ny side for farger i design.nav.no

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#4]
Krav. 
VIse CMYK, RGB og HEX uten klikk
Leke med interaktitet for å vise WCAG
Tab for Bruksområder og prinsipper
Skriv prinsippene @sergiohaisch @weiqing3
copiere hex verdien uten å åpne vinduet

**Comment by sergiohaisch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EL & CA: Fargesiden - Design System](https://trello.com/c/2cGI2IGc/461-el-ca-fargesiden-design-system)

**Comment by ghost** [comment]
Nytt tekstforslag og inndeling:
https://docs.google.com/document/d/1Iq6-4DiDuZa1wGwWKIpxJX81SQCN-iNwM63IFNJNAeQ/edit#

**Comment by Lillebo** [comment]
Erstattet av #76
