### ISSUE TITLE
Retningslinjer: Radio buttons

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#44]
Retningslinjer for bruk av de ulike ulike variantene.
Ikke bruk alle de ulike design utrykkene i/på samme flate eller løsning.

![Radio_buttons_ui_design_use](https://user-images.githubusercontent.com/50408627/63445501-bf683100-c438-11e9-8689-0c6500cb4520.png)

**Comment by randisolli** [comment]
Denne er fikset i design.nav.no, de som er "avhuket" er fjernet.
