### ISSUE TITLE
Retningslinjer: Tilganger (Lisenser) til Zeplin

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#45]
Publiseres under prosjekt oversikt https://design.nav.no/resources/new-project

Tekst som skal publiseres:
https://docs.google.com/document/d/1GNoGesYv3vZfAFsyl2vt64sJI9SEfzkEGfNwmY5GVWc/edit?usp=sharing

**Comment by randisolli** [comment]
Vi bruker ikke lenger Zeplin.
