### ISSUE TITLE
Accessibility info på Lenkepanel

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#46]
Skrive føringer under accessibility fanen https://design.nav.no/components/lenkepanel/accessibility

Ser også på plassering av av chevron da plassering av chevron som er i dag er ikke bra for folk med skjermforstørrer blant annet.

Se på å flytte chevron på venstresiden eller rett ved tekstslutt.

Kan nok dessverre se litt rotete ut hvis noen paneler har lenker og noen ikke. Samtidig blir det lettere å skjønne hva som er klikkbar
Vurder litt like muligheter, og tester ut ulike design forslag.

**Comment by karinaldw** [comment]
@chrisarnesen setter du opp noen forslag? 
Funka bruker pil foran tekst, uu.difi.no pil rett etter tekst.

**Comment by Lillebo** [comment]
Duplikat #47
