### ISSUE TITLE
Chevron plassering på linker og lenkepanel – utfordring ved skjermforstørrer

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#47]
Se på plassering av chevron, da plassering av chevron som er i dag er ikke bra for folk med skjermforstørrer blant annet.

Se på å flytte chevron på venstresiden eller rett ved tekstslutt.

Kan nok dessverre se litt rotete ut hvis noen paneler har lenker og noen ikke. Samtidig blir det lettere å skjønne hva som er klikkbar
Vurder litt like muligheter, og tester ut ulike design forslag.

**Comment by randisolli** [comment]
duplicate #26
