### ISSUE TITLE
Støtte for lenker med ikon

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#54]
specs: 

- Uten padding
- Mulighet for ikon før eller etter
- Trenger guidlines for bruk: Når skal, eller ikke skal brukes. Kodet som lenke eller knapp?
- Visuelle guidelines
- Sett med ferdig knapper.

**Comment by Lillebo** [comment]
Løst: https://design.nav.no/components/lenke#med-ikon
