### ISSUE TITLE
Lenke til begrepskatalogen

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#56]

**Comment by randisolli** [comment]
https://data.nav.no/?size=n_30_n&filters%5B0%5D%5Bfield%5D=tittel&filters%5B0%5D%5Bvalues%5D%5B0%5D=&filters%5B0%5D%5Btype%5D=any&filters%5B1%5D%5Bfield%5D=format&filters%5B1%5D%5Bvalues%5D%5B0%5D=godkjent_begrep&filters%5B1%5D%5Btype%5D=all

**Comment by KenAJoh** [comment]
Fullført med navikt/nav-frontend-moduler#753
