### ISSUE TITLE
Eksempler og live previews

### ISSUE THREAD

**Issue by sergiohaisch** [navikt/Designsystemet-old#57]

**Comment by sergiohaisch** [comment]
Ala https://design-system.service.gov.uk/patterns/

**Comment by Lillebo** [comment]
Duplikat av #19. Vi bør nok heller opprette egne issues per mønster. Denne typen issues som omhandler mange ting samtidig er vanskelig å "fullføre" og har en tendens til å forbli åpen veldig lenge.
