### ISSUE TITLE
Side om tilgjengelighet og universell utforming

### ISSUE THREAD

**Issue by karinaldw** [navikt/Designsystemet-old#6]
Legg ut siden som er på https://confluence.adeo.no/pages/viewpage.action?pageId=324403831 ut på design.nav.no. 
Bildet ligger på https://trello-attachments.s3.amazonaws.com/590c618893f382eb61038bae/5cd521f3fcef445130ce8c6e/c85a5d6ea8a90aad7dd28dd3471009fb/uu-illustrasjon2.jpg (husk å ta med alt-tekst)

**Comment by karinaldw** [comment]
Gist på https://github.com/navikt/Designsystemet/blob/master/uu-intro.md

**Comment by sergiohaisch** [comment]
Status på denne @karinaldw @Lillebo?

**Comment by karinaldw** [comment]
Veldig godt spørsmål :)

**Comment by Lillebo** [comment]
Forhåndsvisning av disse sidene som de er nå: http://archivedworks.com/dev/nav/nye-docs/

**Subdomener** (#18)
Gå til: Ressurser -> Subdomener

Good to go :+1:

**Tilgjengelighet i NAV** (#6)
Gå til: Tilgjengelighet -> Tilgjengelighet i NAV

Gjenstår:
- Legge inn illustrasjoner i tabellen

**Alt-tekster** (#7)
Gå til: Tilgjengelighet -> Alt-tekster

Gjenstår:
- Legge inn info-boks om begreper
- Gjenstår å legge inn NAV-relaterte eksempler

Vi kan gjerne publisere som de er nå, og heller legge til det som gjenstår senere når vi får tid. Som dere vet er jeg veldig opptatt med å veilede sommerstudentene disse ukene.

**Comment by Lillebo** [comment]
Publisert: https://design.nav.no/accessibility/overview
