### ISSUE TITLE
Alt-tekst-retningslinjer

### ISSUE THREAD

**Issue by karinaldw** [navikt/Designsystemet-old#7]
Ligger nå på https://confluence.adeo.no/pages/viewpage.action?pageId=322910549.
Husk å kode alt-tekst-beslutningstre som liste (som på https://www.w3.org/WAI/tutorials/images/decision-tree/). 
Bildene ligger i https://www.dropbox.com/sh/b07oxruzzuyrinj/AADmv0bqVoflvbrzIvFx2ucPa?dl=0

**Comment by karinaldw** [comment]
Har lagt inn gist på https://github.com/navikt/Designsystemet/blob/master/uu-alt-tekster.md

Har prøvd å sette opp beslutningstreet som på https://www.w3.org/WAI/tutorials/images/decision-tree/, men vanskelig å se når man ikke ser selve koden. Hadde vært bra hvis vi fikk stylet den på samme måte som W3C.

**Comment by Lillebo** [comment]
Publisert: https://design.nav.no/accessibility/alt-text
