### ISSUE TITLE
Forbedringer til ekspanderbart panel

### ISSUE THREAD

**Issue by PrebenAas** [navikt/Designsystemet-old#73]
Front end-modulen "ekspanderbart panel" fungerer som ønsket i prod/kode, men hadde vært fint å hatt den samme muligheten i Sketch. Jeg savner å kunne legge inn tekst-override, samt å snu chevron (velge chevron opp/ned) i overrides.

Issue #33 viser også noe av det samme problemet, men tror ikke alt ble løst av det @chrisarnesen kommenterte.

![ekspanderbart panel](https://user-images.githubusercontent.com/20104610/65669411-c855af00-e043-11e9-86ea-f2efa96f3c19.png)

**Comment by Lillebo** [comment]
Skal være fikset med [denne Sketch-oppdateringen](https://nav-it.slack.com/archives/C7NE7A8UF/p1580898940061600).
