### ISSUE TITLE
Undernavigasjon (faner) i selve Designsystemet forsvinner når du blader nedover

### ISSUE THREAD

**Issue by finiteattention** [navikt/Designsystemet-old#74]
Her i selve Designsystemet bruker vi faner innen en bestemt seksjon. For eksempel: Ressurser > Språk > Skriveråd (se vedlegg)

Når jeg er i ferd med å lese meg gjennom "Skriveråd" fanen, forsvinner alle fanene, og jeg vet ikke hvor jeg er lenger. Jeg må blade langt oppover igjen for å se at andre faner finnes engang. Her ville det vært kjekt med flytende faner som alltid vises uansett hvor på siden du befinner deg. Eller eventuelt gjentakelse av fanene eller en CTA til å gå videre til neste fane helt i bunn, men dupliserte CTA'er på en side er jeg vel mindre fan av.

<img width="1430" alt="Skjermbilde 2019-10-03 kl  09 54 22" src="https://user-images.githubusercontent.com/6875491/66109058-26464180-e5c4-11e9-9812-622cadba3522.png">
<img width="1432" alt="Skjermbilde 2019-10-03 kl  09 54 09" src="https://user-images.githubusercontent.com/6875491/66109059-26464180-e5c4-11e9-9d16-ac5b805181f5.png">

**Comment by Lillebo** [comment]
Duplikat av #75
