### ISSUE TITLE
Tomme, unødvendige pixler i symbols gjør symbolet større

### ISSUE THREAD

**Issue by PrebenAas** [navikt/Designsystemet-old#79]
Har funnet noen symbols der det er lagt til en eller to ekstra pixler under ikonet som i utgangspunktet skal være kvadratiske, men nå blir feks 24x25 (og ikke 24x24). Dette er pirk, men gjør at jeg må detache symbolene hvis jeg jobber med presise skisser i Sketch.

Under har jeg markert alle ikonene, slik at dere ser hva jeg mener:

![Screenshot 2019-10-08 at 11 31 58](https://user-images.githubusercontent.com/20104610/66384691-81f73d00-e9bf-11e9-81c6-17bbd3ec8b69.png)

**Comment by sergiohaisch** [comment]
Hei @PrebenAas, årsaken at noen av kvadratiske ikonene har en piksel ekstra var for å begrense ikon valg i høyre parametrepanel i Sketch. Om du valgt f.eks en alertstripe kunne du bytte ikonen, og du fikk mulighet til velge fra alle ikoner eller elementer som hadde samme størrelse. dvs, hele ikon biblioteket (hvor ikonene er 24x24), inkl chekboksen og radios (gitt 24x24 at det hadde størrelse). Det er derfor vi laget en hack som begrenset valget. Etter Sketch 58 kan det bli mulig å unngå problemet, vi har bare ikke kommet så langt til å teste en fiks. Om du får en abstract lisens kan du sikkert fikse problemet selv, lag en branch og sette meg og og Wei for en review. Du kan sende en mail til @fredrik.scheide for å høre mer om lisensene.
