### ISSUE TITLE
Aria-varsling og visuell indikator på textarea (x tegn igjen)

### ISSUE THREAD

**Issue by karinaldw** [navikt/Designsystemet-old#8]
Få inn aria-live polite igjen. Les opp når det er 50, 40, 30, 20, 10 og 0 tegn igjen (og når man har gått over maks antall tegn)

Man må og få en visuell indikasjon når man går over maks antall tegn.

**Comment by Lillebo** [comment]
Vi har allerede `aria-live="polite"` ved følgende situasjoner:

- Når det er 5 tegn igjen
- Når det er 0 tegn igjen

Når bruker har skrevet for mange tegn endres dette til `aria-live="assertive"` som vedvarer sålenge bruker har brukt for mange tegn.

![Sep-10-2019 13-02-17](https://user-images.githubusercontent.com/74510/64608689-85e96c80-d3cb-11e9-815a-17e1526d0a8d.gif)

Ser at [Gov.uk sin textarea komponent](https://design-system.service.gov.uk/components/character-count/) bruker konstant `aria-live="polite"`, uavhengig av hvor mye tekst brukere har skrevet. Må si jeg liker den måten å løse det på, slik at vi unngår `assertive`.

Enig i at vi bør legge til en visuell markering på tegn-indikatoren når bruker har skrevet for mye 👍

**Comment by Lillebo** [comment]
Forslag: https://nds-textarea-aria-polite.herokuapp.com/components/textarea

**Comment by karinaldw** [comment]
La oss prøve og be om tilbakemeldinger. Innbilder meg at gov.uk testet dette en del med synshemmede og det fungerte bra.

**Comment by Lillebo** [comment]
Fikset: navikt/nav-frontend-moduler#548
