### ISSUE TITLE
Bug i chevron-tekst

### ISSUE THREAD

**Issue by PrebenAas** [navikt/Designsystemet-old#80]
Tekstboks ekspanderes ikke automatisk og forblir venstrestilt. Må ha skjedd ganske nylig. 

![Screenshot 2019-10-11 at 15 12 19](https://user-images.githubusercontent.com/20104610/66654106-cdb51b00-ec39-11e9-8494-cc6d21b336c2.png)

**Comment by Vikingwind** [comment]
Tror det er padding I Sketch som ikke satt riktig
