### ISSUE TITLE
Rammen forsvinner med nytt tekst innhold på standard knapp (40 px)

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#81]
Rammen rundt standard knapp forsvinner i det man skriver.
Fil fra Cloud bibliotek.

<img width="288" alt="ramme_knapp40" src="https://user-images.githubusercontent.com/50408627/66815287-4963e000-ef38-11e9-8521-1b6a2cd9d365.png">

**Comment by Vikingwind** [comment]
Bruk nyeste sketch cloud versjon i stedet Dropbox. Feil ligger i den gamle versjon fra Sergio (SC)
