### ISSUE TITLE
Mønster: Skjemavalidering

### ISSUE THREAD

**Issue by Lillebo** [navikt/Designsystemet-old#82]
NAV har noen særegne regler for skjemavalidering. Noen av disse reglene har vist seg å være litt ufullstendige og forvirrende (ref. [Slack-diskusjon](https://nav-it.slack.com/archives/C6HJFRRMY/p1567774888041100)). Vi trenger å lage et mønster for å demonstrere hvordan dette skal/bør fungere.

**Comment by Lillebo** [comment]
Avhengig av #83

**Comment by Lillebo** [comment]
Da har jeg forsøkt å lage noen mønster basert på de retningslinjene vi har hatt frem til nå. Slik jeg ser det kan disse retningslinjene tolkes og implementeres på 4 forskjellige måter:

**Alternativ A**: http://nds-pattern-validering-a.herokuapp.com/patterns/form-validation
**Alternativ B**: http://nds-pattern-validering-b.herokuapp.com/patterns/form-validation
**Alternativ C**: http://nds-pattern-validering-c.herokuapp.com/patterns/form-validation
**Alternativ D**: http://nds-pattern-validering-d.herokuapp.com/patterns/form-validation

En mer detaljert beskrivelse av hvilke retningslinjer som gjelder for hvert av alternativene står inne på lenken under overskriften "retningslinjer". Ulikhetene handler i hovedsak om *når* inline validering skal forekomme og hvordan feiloppsummeringsboksen skal se ut og oppføre seg. Det bør nevnes at de to siste alternativene kan være krevende å implementere for utviklerne våre - som igjen kan medføre en viss risiko for at retningslinjene ikke blir etterlevd.

Tror det kan være lurt om vi samles for å diskutere de forskjellige alternativene, men kom gjerne med innspill og kommentarer fortløpende.

@Miaag @karinaldw @unorsk @DeamonDavid @nutgaard

**Comment by unorsk** [comment]
Jeg er litt usikker på at den boksen med feil-oppsummeringen funker bra på mobil, siden det er lite plass på skjermen og er litt vanskelig å få oversikt over hele skjema og bruker må hoppe fram og tilbake for å fikse alle feil.

Også ser det litt mer logisk å plassere den boksen feil-tekster rett over Submit-knappen, slik at bruker slipper å skrolle opp fram til begynnelsen.

Og (selvfølgelig) har jeg en alternativ ideé om hvordan skjemaer kan se ut: hvis man har et enkelt skjema (som består av noen få elementer som ikke tar mer plass enn én skjerm) da viser vi feil-tekst kun ved relevante felter. Men har vi et komplekst og stort skjema, da må det splittes i 1-2-3-X steg som kan fylles ut et steg om gangen.

**Comment by Lillebo** [comment]
Hm, tror ikke det er noe alternativ å droppe den feiloppsummeringsboksen. Den må nok være med av tilgjengelighetshensyn. Det skal heller ikke være nødvendig å scrolle seg frem til den da den automatisk skal få fokus når den først dukker opp.

Men du har rett i at disse retningslinjene bør sees i sammenheng med andre typer skjema; som f.eks. de vi deler opp i individuelle steg. Slik jeg har skjønt det så skal feiloppsummeringsboksen bare vises om skjemaet har 2 eller flere felter.

**Comment by unorsk** [comment]
Skjønner veldig godt at vi bør ta tilgjengelighet til hensyn. Men er litt uenig at en løsning som scroller seg automatisk opp til feiloppsummeringsboksen er mer tilgjengelig enn feiloppsummeringsboksen som ligger rett over/ved/under submit-knappen.

Det er litt uklart for meg hvilken validering strategi vi har. Det er enten lov å taste inn hva som helst og etter det gjør vi validering. Ellers kan vi forbi å taste inn feil data. Som f.eks dato (den kan sjekkes mens man taster inn) eller navn (kan ikke ha tall eller andre symboler borsett fra bokstaver, mellomrom og '-') eller email osv.
Da nesten alltid validering kokes ned til påkrevde felt. 

Forresten, rødt bakgrunn i input som ikke er valid ser ut som at input er disabled (jeg opplever det slik).

**Comment by nutgaard** [comment]
Etter det jeg har forstått retningslinjene tidligere så er det en kombinasjon av forslag a og b som har vært standard. Løsning A er nok nærmest det jeg mener har vært retningslinjene, men ser ut som oppsummeringsboksen dukker opp når man reintroduserer en feil og den har vært gyldig. 

Kastet sammen ett bibliotek for FO for en stund tilbake som etterlever den gamle standarden om det er av interesse; https://github.com/nutgaard/use-formstate

**Comment by Miaag** [comment]
**Notater og takeaways fra møte med UU:**
- Automatisk scrolling opp til oppsummering av feil, er usikkert mtp på tilgjengeligspersp. (ubehagelig, kan trigge anfall).
- Positiv til oppsummeringsfelt med input feil
- Forslag: Legg til rød strek ved siden av inputfeltene, fet rød outline rundt inputfeltene, med sterk rød fet tekst under inputfeltet, samt fjerne rød bakgrunnsfarge.
- Legge til ikon ved siden av feil teksten(?)
- Knapp for validering av skjema før man sender inn(?) Som gir en oppsummering før man sender inn.
- Ved større skjemaer - Plassere oppsummering også nederst i skjemaet(?) Eventuelt kontekstuelt nederst på siden ifb med action knapper.
- Vurdere "lagre kladd" funksjonalitet
- Utforske forskjellen mellom regelsett ifb med stort skjema, mindre skjemaer og skjemaer gruppert etter tema.

**Comment by Lillebo** [comment]
Har laget 2 nye prototyper med følgende endringer:
- Fjernet rosa bakgrunnsfarge på inputfelt med feil
- Inputfelt med feil markeres med `2px` rød border
- Endret feilmelding under inputfelter fra å være italic til bold
- Endret slik at alle skjemalabels nå er bold
- Feiloppsummeringsboks er flyttet fra toppen til bunnen av skjema (over submit-knappen)
- Fjernet bakgrunnsfarge i feiloppsummeringsboks, og gitt denne en `4px` tykk border

<img width="954" alt="Screenshot 2019-12-12 at 15 47 30" src="https://user-images.githubusercontent.com/74510/70721956-bf958080-1cf6-11ea-9176-54a4a4f6175e.png">

Forskjellen på disse 2 er at den ene også inkluderer en feilmarkering med `4px` tykk vertikal rød border til venstre ([slik som Gov.uk gjør det](https://design-system.service.gov.uk/components/error-message/)).

**Alternativ E:** https://nds-pattern-validering-e.herokuapp.com/patterns/form-validation
**Alternativ F:** https://nds-pattern-validering-f.herokuapp.com/patterns/form-validation

**Comment by Lillebo** [comment]
Etter en kjapp samtale med @karinaldw ble vi enige om at det ikke er nødvendig med den `4px` tykke vertikale borderen til venstre, og at denne kan greit utelukkes hvis det forenkler det tekniske og reglene.

Hun hadde også et innspill om at det kanskje hadde vært best hvis brukeren slapp å tabbe seg gjennom feil-listen på nytt før de kommer til submit-knappen etter å ha utbedret feilene i skjemaet. Det er jeg enig i, og har da laget en siste versjon basert på alternativ F ovenfor hvor feilene i feiloppsummeringsboksen forsvinner etterhvert som de blir utbedret:

**Alternativ G:** https://nds-pattern-validering-g.herokuapp.com/patterns/form-validation

**Comment by Lillebo** [comment]
Løst med denne: https://github.com/navikt/nav-frontend-moduler/pull/641

**Comment by PrebenAas** [comment]
@Lillebo Har ventet med å kommentere her pga. Heroku-appen, som har vært nede lenge. Nå er den oppe og kjører igjen, og du kan da klikke deg gjennom for å se hvordan vi har løst "skjemautfylling" og avtaleinngåelse i ett.

https://tiltaksgjennomforing.herokuapp.com/

**Comment by Lillebo** [comment]
Null stress @PrebenAas. Og takk for at du deler 🙂

Ser egentlig ikke noe problem med måten dere har strukturert dette på. Slik jeg ser det så har dere egentlig mange individuelle skjema - ett for hvert av tabene/sidene - som heller settes sammen på baksiden i etterkant. Hvert skjema har f.eks. en "Lagre"-knapp i bunnen (som da egentlig er skjemaets "Submit"-knapp).

Da tenker jeg det skal være godt mulig å implementere våre retningslinjer for validering på hver av disse tabene/sidene/stegene.
