### ISSUE TITLE
Modal – Ulike varianter

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#84]
Ligger to ulike design på Modal i Sketch.    Er tanken at begge skal inn som kode?  For i dag ligger det kun 1 i frontend.

<img width="582" alt="modal_Sketch" src="https://user-images.githubusercontent.com/50408627/66921108-d6846300-f024-11e9-97bf-bd9b3a66b09f.png">

VS

https://design.nav.no/components/modal

**Comment by randisolli** [comment]
@Vikingwind fjerne øverste variant med "Veileder" i Sketch.
