### ISSUE TITLE
Fikse fleksibilitet i Tabs

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#85]
Det ser ut som det har skjedd noe med Tabs, nå ligger de ligger ikke lenger sentret i feltet lenger, men blir høyre justert og de "sprenger" feltet om ordet er for langt.

Gjelder Cloud versjonen.

**Comment by randisolli** [comment]
@Vikingwind , sjekk om det er et problem fortsatt.

**Comment by randisolli** [comment]
Sjekket i Sketch, og ser at det er fikset nå.
