### ISSUE TITLE
Mobilversjon: Dropdown meny på mobilløsning forsvinner ikke ved valgt meny inngang

### ISSUE THREAD

**Issue by ghost** [navikt/Designsystemet-old#86]
Dropdown meny i mobilløsning forsvinner ikke ved valgt side inngang.

Når man velger en side, f.eks Språk i dropdown menyen, bør da menyen forsvinne, uten at man trenger å trykke på «X» for å komme til sideinnholdet.

Mobil er mulig ikke hovedplattformen for de som bruker tjenesten?

**Comment by KenAJoh** [comment]
Fikset i nytt oppsett
