### ISSUE TITLE
Ta i bruk github issue-templates

### ISSUE THREAD

**Issue by unorsk** [navikt/Designsystemet-old#89]
[Mer om github issue-templates](https://help.github.com/en/github/building-a-strong-community/creating-issue-templates-for-your-repository)

### Godt at vi kan ta det i bruk til

1. Bugs
2. Feature requests
3. Questions
4. Annet?

### Poenget er at det blir 

1. Enklere for våre brukere/oss å lage nye issues
2. Issues skal se litt mer konsistent ut (f.eks Bugs kan ha seksjoner som `hva er feil`, `hva forventes`, `hvordan gjenskapes det` og `forslag`)

**Comment by KenAJoh** [comment]
Nav-frontend-moduler bruker nå Issue templates.
