### ISSUE TITLE
Verktøyside for uu-testing

### ISSUE THREAD

**Issue by karinaldw** [navikt/Designsystemet-old#9]

**Comment by karinaldw** [comment]
Legge ut informasjon som nå er på https://confluence.adeo.no/pages/viewpage.action?pageId=324404234.

Si helst ifra når du holder på med jobben, siden vi oppdaterer av og til. Vi må og da stenge confluence-siden når innholdet er på design.nav.no og redirecte.

**Comment by karinaldw** [comment]
Gist: https://github.com/navikt/Designsystemet/blob/master/uu-testverkt%C3%B8y.md

**Comment by Lillebo** [comment]
Har implementert 2 versjoner av denne:

**Alternativ A**: http://archivedworks.com/dev/nav/a11y-docs/
**Alternativ B**: http://archivedworks.com/dev/nav/a11y-docs-alt/

Gå til `Tilgjengelighet` -> `Verktøy for UU-testing` for å se sidene.

Syntes kanskje alternativ A ble litt rotete og vanskelig å lese med alle de videoene og bildene, så jeg laget alternativ B som en forhåpentligvis litt mer lettlest og oversiktlig variant. 

Er også litt i tvil om vi egentlig burde liste opp så mange forskjellige verktøy. Er redd folk kan bli veldig usikre på hvilke verktøy de burde teste, og at de kommer til å bruke mye tid på å prøve og sammeligne mange av dem. F.eks. er det ganske vanskelig å skjønne hva som skiller Lighthouse fra ARC eller WAVE. Burde vi kanskje begrense denne listen en smule, og heller komme med noen klare anbefalinger?

**Comment by karinaldw** [comment]
Hei

Vi synes det er viktig å ha med videoer, men de må nok ikke være så store.
Ellers bra 😊

/Karina

Fra: Eirik Lillebo <notifications@github.com>
Svar til: navikt/Designsystemet <reply@reply.github.com>
Dato: torsdag 8. august 2019 12:38
Til: navikt/Designsystemet <Designsystemet@noreply.github.com>
Kopi: "Ludwig, Karina" <Karina.Ludwig@nav.no>, Author <author@noreply.github.com>
Emne: Re: [navikt/Designsystemet] Verktøyside for uu-testing (#9)


Har implementert 2 versjoner av denne:

Alternativ A: http://archivedworks.com/dev/nav/a11y-docs/<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Farchivedworks.com%2Fdev%2Fnav%2Fa11y-docs%2F&data=02%7C01%7CKarina.Ludwig%40nav.no%7Ccb8069eff4004a389f0008d71bec994f%7C623665341ec3496288699b5535279d0b%7C1%7C0%7C637008575311731152&sdata=m69DF8%2F587mRVREaNYgQAI%2B0%2F7AhFbaxGcmkMzCtRUI%3D&reserved=0>
Alternativ B: http://archivedworks.com/dev/nav/a11y-docs-alt/<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Farchivedworks.com%2Fdev%2Fnav%2Fa11y-docs-alt%2F&data=02%7C01%7CKarina.Ludwig%40nav.no%7Ccb8069eff4004a389f0008d71bec994f%7C623665341ec3496288699b5535279d0b%7C1%7C0%7C637008575311736144&sdata=V0GvGrfwOtbXWkG%2BOilpWt%2BJbW%2BAwnpFJob5jMMSu20%3D&reserved=0>

Gå til Tilgjengelighet -> Verktøy for UU-testing for å se sidene.

Syntes kanskje alternativ A ble litt rotete og vanskelig å lese med alle de videoene og bildene, så jeg laget alternativ B som en forhåpentligvis litt mer lettlest og oversiktlig variant.

Er også litt i tvil om vi egentlig burde liste opp så mange forskjellige verktøy. Er redd folk kan bli veldig usikre på hvilke verktøy de burde teste, og at de kommer til å bruke mye tid på å prøve og sammeligne mange av dem. F.eks. er det ganske vanskelig å skjønne hva som skiller Lighthouse fra ARC eller WAVE. Burde vi kanskje begrense denne listen en smule, og heller komme med noen klare anbefalinger?

**Comment by ghost** [comment]
Alternativ A eller B, med eller uten video. 

Alternativ B er mye ryddigere uttrykk, lettere å se og scanne siden, men synes viktig å ha med videoene. Video gjør det lettere å forstå «komplekst materiale».

Er det ikke mulig å ta bort «embed video preview», men heller ha en en link, se forklarende video her?
Det samme gjelder med alle skjermbildene 😊

Alternativ A: http://archivedworks.com/dev/nav/a11y-docs/
Alternativ B: http://archivedworks.com/dev/nav/a11y-docs-alt/

**Comment by Lillebo** [comment]
Har laget en ny versjon av alternativ B hvor jeg har prøvd å ta med videoene som tekst-lenker under de forskjellige verktøyene: http://nds-a11y-tools.herokuapp.com/accessibility/tools (siden kan bruke litt tid på laste)

**Comment by Lillebo** [comment]
Løst: https://design.nav.no/accessibility/tools
