### ISSUE TITLE
Oppdatere sketchkomponent "tegnteller"

### ISSUE THREAD

**Issue by ElinNav** [navikt/Designsystemet-old#90]
Gjøre det mulig å skrive lengre tekst i tegnteller feltet.
![Screenshot 2019-10-24 at 12 07 53](https://user-images.githubusercontent.com/48942744/67476398-4663a080-f658-11e9-97d1-cdf97c52c8c7.png)

**Comment by karinaldw** [comment]
1) Også i sketch så må det være tydelig label. 

2) Teknisk sett skal vi ikke ha en placeholder. Man skal jo da heller ikke ha placeholder i sketch?

**Comment by Vikingwind** [comment]
De er fikset.

**Comment by Lillebo** [comment]
Er denne fiksen publisert på design.nav.no? Hvis ikke tror jeg vi kan vente med å lukke issuet inntil ny versjon er tilgjengelig for andre.
