### ISSUE TITLE
Størrelse på input-komponenter fra 40 til 32px høyde (for interne flater)

### ISSUE THREAD

**Issue by Lilyngs** [navikt/Designsystemet-old#97]
Som vi har diskutert tidligere er det nå behov for å tilby input-komponenter i størrelse 32px høyde. I tillegg er det behov for at label kan flyttes til venstre side slik at man sparer plass i høyden, og at label kan velges bort.

Det skal ikke være behov for å lage skisser på dette.

**Comment by Lillebo** [comment]
Løst i denne: https://github.com/navikt/nav-frontend-moduler/pull/641
